
python2to3:
  clone: False
  pylint-before-futurize: False
  futurize: False
  path: /home/dmitry/zeev-stxnet/Tools_AutoBuild_1108_1740-19-08-2020-17-59-46-484309
  exclude:
  replace-in-files:
    src:
    dest:
