
python2to3:
  clone: False
  pylint-before-futurize: True
  futurize: True
  path: /home/dmitry/zeev/ToolsPyMigration-21-01-2021-13-09-02-476911
  exclude:
    - venv
    - venv2
    - .idea
    - Mac
    - External
    - Libraries
